version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Root directory of the project
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
